[programs.devnet]
newtut = "5n1fP65uWvoLpmWfzbGgpyD5kVX3mnVfJgBfy5NzdEbn"


[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/kapil/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
